<!-- start header -->
<?php include_once appRoot."/Views/layouts/header.php" ?>
<!-- end header -->
<!-- start navbar -->
<?php include_once appRoot."/Views/layouts/navbar.php" ?>
<!-- end navbar -->
<!-- start slider -->
<?php include_once appRoot."/Views/layouts/slider.php" ?>
<!-- end slider -->
<!-- start catProduct -->
<?php include_once appRoot."/Views/layouts/catProduct.php" ?>
<!-- end catProduct -->
<!-- end slider -->
<!-- start footer -->
<?php include_once appRoot."/Views/layouts/footer.php" ?>
<!-- end footer -->
